### ISSUE TITLE
how to know that I use mintty programmatically ?

### ISSUE THREAD

**Issue by vtorri** [mintty/utils#4]
I have read in the wiki that there is a shell script that can detect if I am in mintty (or cygwin or msys2).

But I would like to know if it is possible to detect if i'm in mintty programmatically.

 More precisely, i would like to know if I use cmd,  or mintty (or any of its variants).

**Comment by mintty** [comment]
You'd send escape sequence `^[[>c` to the terminal and check the response, after adjusting tty properties to receive a raw response (esp. not in "cooked" line mode).
How to do it from a command line shell is demonstrated in the `terminal` script; for mintty, its output is:
77 mintty 30603 0

**Comment by vtorri** [comment]
see other issue, closing
